# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
logo-prefix: XMD
logo-suffix: PLUS
title:
    ko: 도움말
    ja: ヘルプ
    zh_CN: 帮助
email: dev@xmd.co.kr
description:
    ko: > # XMDPLUS 도움말.
    ja: > # XMDPLUS ヘルプ。
    zh_CN: > # XMDPLUS 帮助。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xmdplus.github.io" # the base hostname & protocol for your site
# url: "http://localhost:3000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#   hard_wrap: false
# highlighter: rouge

list_header:
    ko: 도움말 리스트
    ja: ヘルプリスト
    zh_CN: 帮助目录

index_content:
    ko: XMD PLUS 서비스 사용 도움말입니다.
    ja: XMD PLUSサービス利用のヒントです。
    zh_CN: XMD PLUS服务使用的帮助。

gems:
    - jekyll-polyglot

languages: ["ko", "ja", "zh_CN"]
default_lang: "ko"
exclude_from_localization: ["javascript", "images", "css", "bootstrap", "dist", "plugins", "_data"]
parallel_localization: true

category:
    ko:
        # - 회원사 정보관리
        # - 사용자 관리
        # - 코드 관리
        - 상품 관리
        - 매장 관리
        # - 고객 관리
        - 재고 관리
        # - 판매 분석
        - POS
    ja:
        # - 회원사 정보관리
        # - 사용자 관리
        # - 코드 관리
        - 商品管理
        - 店舗管理
        # - 고객 관리
        - 在庫管理
        # - 판매 분석
        - POS_ja
    zh_CN:
        # - 회원사 정보관리
        # - 사용자 관리
        # - 코드 관리
        - 商品管理_zh
        - 卖场管理
        # - 고객 관리
        - 库存管理
        # - 판매 분석
        - POS_zh
