# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
logo-prefix: XMD
logo-suffix: PLUS
title: 도움말
email: dev@xmd.co.kr
description: > # XMDPLUS 사용자 메뉴얼.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://xmdplus.github.io" # the base hostname & protocol for your site
url: "http://localhost:3000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
#   hard_wrap: false
# highlighter: rouge
category:
    # - 회원사 정보관리
    # - 사용자 관리
    # - 코드 관리
    - 상품 관리
    - 매장 관리
    # - 고객 관리
    - 재고 관리
    # - 판매 분석
    - POS
